FROM mcr.microsoft.com/powershell:lts-nanoserver-ltsc2022
MAINTAINER support@oneidentity.com

COPY ["*.ps1", "c:/temp/safeguard/"]
COPY ["src/", "c:/temp/safeguard/src/"]

RUN pwsh -NoProfile -Command "C:\temp\safeguard\install-local.ps1 'C:\Program Files\PowerShell\Modules'"

ENTRYPOINT [ "pwsh" ]
CMD ["-NoExit", "-Command", "Get-SafeguardBanner"]